### ISSUE TITLE
关于指标Average Forgetting Rate的疑问

### ISSUE THREAD

**Issue by longlongman** [wutong8023/AAAI-CML#1]
很高兴能读到这篇出色的工作，对我很有启发，但是对于文章中设计的Average Forgetting Rate指标我不太理解，请问能详细解释下这个指标的含义吗？它为什么能衡量模型对顺序的敏感性？

**Comment by wutong8023** [comment]
该指标描述的是 随机生成多组序列(T_{0:N})，其中固定id的任务T_i 可能在不同的序列中出现在不同的位置。我们P(T_i) = p的所有序列取全部任务输入后T_i准确率的平均值。也就是一个任务在某一个位置的平均表现。

**Comment by wutong8023** [comment]
该指标基于模型表现倒推一个任务是不是比较困难，由于它衡量的是任务级别的表现而不是序列级别的表现，所以单个指标并不能反映顺序敏感性。这个指标被设计主要用来衡量外部知识是否发挥了作用，顺序敏感性的指标是统计量 error bound
